# Generated by Django 5.1 on 2024-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobskill1', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(default='Descrpcion random', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='objetivo',
            field=models.CharField(default='Objetivo random', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apellido2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='media/1.jpg', upload_to='Usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
    ]
